# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: erc-contacts 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "erc-contacts".freeze
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Mislav Marohnic".freeze, "George Odata".freeze, "Julian Countu".freeze]
  s.date = "2020-01-24"
  s.description = "Import users' contacts lists from Google, Yahoo!, and Windows Live.".freeze
  s.email = "kulesa@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".gitmodules",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "erc-contacts.gemspec",
    "lib/contacts.rb",
    "lib/contacts/consumer.rb",
    "lib/contacts/google.rb",
    "lib/contacts/oauth_consumer.rb",
    "lib/contacts/railtie.rb",
    "lib/contacts/util.rb",
    "lib/contacts/version.rb",
    "lib/contacts/windows_live.rb",
    "lib/contacts/yahoo.rb",
    "pkg/erc-contacts-0.3.0.gem",
    "pkg/kulesa-contacts-0.2.6.gem",
    "spec/config/contacts.yml",
    "spec/contact_spec.rb",
    "spec/feeds/google-many.xml",
    "spec/feeds/wl_contacts.xml",
    "spec/feeds/yh_contacts.txt",
    "spec/gmail/google_spec.rb",
    "spec/spec_helper.rb",
    "spec/windows_live/windows_live_spec.rb",
    "spec/yahoo/yahoo_spec.rb"
  ]
  s.homepage = "https://github.com/kulesa/contacts".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.8".freeze
  s.summary = "Import users' contacts lists from Google, Yahoo!, and Windows Live.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<hpricot>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>.freeze, ["~> 1.10.7"])
      s.add_runtime_dependency(%q<oauth>.freeze, ["~> 0.4.5"])
      s.add_runtime_dependency(%q<oj>.freeze, ["~> 3.0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.6.0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3.7"])
      s.add_development_dependency(%q<mocha>.freeze, [">= 0"])
      s.add_development_dependency(%q<fakeweb>.freeze, [">= 0"])
    else
      s.add_dependency(%q<httparty>.freeze, [">= 0"])
      s.add_dependency(%q<hpricot>.freeze, [">= 0"])
      s.add_dependency(%q<nokogiri>.freeze, ["~> 1.10.7"])
      s.add_dependency(%q<oauth>.freeze, ["~> 0.4.5"])
      s.add_dependency(%q<oj>.freeze, ["~> 3.0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3.6.0"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.7"])
      s.add_dependency(%q<mocha>.freeze, [">= 0"])
      s.add_dependency(%q<fakeweb>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>.freeze, [">= 0"])
    s.add_dependency(%q<hpricot>.freeze, [">= 0"])
    s.add_dependency(%q<nokogiri>.freeze, ["~> 1.10.7"])
    s.add_dependency(%q<oauth>.freeze, ["~> 0.4.5"])
    s.add_dependency(%q<oj>.freeze, ["~> 3.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.6.0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.7"])
    s.add_dependency(%q<mocha>.freeze, [">= 0"])
    s.add_dependency(%q<fakeweb>.freeze, [">= 0"])
  end
end

